#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mixer-tools
Version  : 3.1.0
Release  : 47
URL      : https://github.com/clearlinux/mixer-tools/releases/download/v3.1.0/mixer-tools-3.1.0.tar.gz
Source0  : https://github.com/clearlinux/mixer-tools/releases/download/v3.1.0/mixer-tools-3.1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mixer-tools-bin
Requires: mixer-tools-data
BuildRequires : go

%description
This project contains tooling for using the software update mixer.

%package bin
Summary: bin components for the mixer-tools package.
Group: Binaries
Requires: mixer-tools-data

%description bin
bin components for the mixer-tools package.


%package data
Summary: data components for the mixer-tools package.
Group: Data

%description data
data components for the mixer-tools package.


%prep
%setup -q -n mixer-tools-3.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1503709622
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1503709622
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mixer
/usr/bin/mixer-pack-maker.sh
/usr/bin/mixer-superpack-maker.sh

%files data
%defattr(-,root,root,-)
/usr/share/defaults/mixer/yum.conf.in
